apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node-app-deployment
  labels: 
    app: nodeappdemo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nodeappdemo
  template:
    metadata: 
     labels: 
        app: nodeappdemo
    spec:
      containers: 
        - name: nodeapp-container
          image: smitalipatekar/nodeappdemo
          ports: 
          - containerPort: 80
