name: Build Docker Image

on:
  push:
    branches:
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

       - name: Login to Docker Hub
         run:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build -t smitalipatekar/nodeappdemo .
    
    - name: Push the Docker image to Docker Hub
      run: docker push smitalipatekar/nodeappdemo
