apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.name }}
  namspace: {{ .Values.namspace }}
  labels: 
    app: {{ .Values.name }}
spec:
  replicas: 5
  selector:
    matchLabels: 
      app: {{ .Values.name }}
  template:
    metadata: 
     labels: 
        app: {{ .Values.name }}
    spec:
      containers: 
        - name: nodeapp-container
          image: "{{ .Values.image.name}}:{{ .Values.image.tag}}"
          ports: 
          - containerPort: 80
